module.exports = async function seedDocumentType(db) {
  try {
    const count = await db.documentType.count();

    if (count === 0) {
      await db.documentType.bulkCreate(
        [
        {
            ID: 5,
            Code: 'CCI',
            Name: 'Community Tax',
            DocumentTypeCategoryID: 1,
            Prefix: 'CCI',
            StartNumber: 100,
            CurrentNumber: 100,
            Suffix: '2025',
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 6,
            Code: 'SI',
            Name: 'Service Invoice',
            DocumentTypeCategoryID: 1,
            Prefix: 'SE-IN',
            StartNumber: 500,
            CurrentNumber: 500,
            Suffix: 'Invoice',
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 11,
            Code: 'RPT',
            Name: 'Real Property Tax',
            DocumentTypeCategoryID: 1,
            Prefix: 'RE-PRO',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: null,
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 13,
            Code: 'OBR',
            Name: 'Obligation Request',
            DocumentTypeCategoryID: 1,
            Prefix: 'OBR',
            StartNumber: 152,
            CurrentNumber: 152,
            Suffix: '2025',
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 14,
            Code: 'DV',
            Name: 'Disbursement Voucher',
            DocumentTypeCategoryID: 1,
            Prefix: 'DV',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: null,
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 15,
            Code: 'TO',
            Name: 'Travel Order',
            DocumentTypeCategoryID: 1,
            Prefix: 'TO',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: null,
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 18,
            Code: 'ORB',
            Name: 'Burial Receipt',
            DocumentTypeCategoryID: 1,
            Prefix: 'BU-RE',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: 'AL-CEIPT',
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 19,
            Code: 'MARIAGEOR',
            Name: 'Marriage Receipt',
            DocumentTypeCategoryID: 1,
            Prefix: 'MA-RE',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: 'GE-CEIPT',
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 20,
            Code: 'ARO',
            Name: 'Allotment Release Order',
            DocumentTypeCategoryID: 1,
            Prefix: 'ARO',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: '2025',
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 21,
            Code: 'BS',
            Name: 'Budget Supplemental',
            DocumentTypeCategoryID: 1,
            Prefix: 'BS',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: '2025',
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 22,
            Code: 'BT',
            Name: 'Budget Transfer',
            DocumentTypeCategoryID: 1,
            Prefix: 'BT',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: '2025',
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 23,
            Code: 'JEV',
            Name: 'Journal Entry Voucher',
            DocumentTypeCategoryID: 1,
            Prefix: 'JEV',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: '2025',
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 25,
            Code: 'CH',
            Name: 'Check',
            DocumentTypeCategoryID: 1,
            Prefix: 'CHK',
            StartNumber: 0,
            CurrentNumber: 0,
            Suffix: '2025',
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 26,
            Code: 'FT',
            Name: 'Fund Transfer',
            DocumentTypeCategoryID: 1,
            Prefix: 'FT',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: null,
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 27,
            Code: 'CCIC',
            Name: 'Community Tax Corporate',
            DocumentTypeCategoryID: 1,
            Prefix: 'CCI',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: null,
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 28,
            Code: 'PR',
            Name: 'Purchase Request',
            DocumentTypeCategoryID: 1,
            Prefix: 'PR',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: '2025',
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 30,
            Code: 'PMT',
            Name: 'Public Market Ticketing',
            DocumentTypeCategoryID: 1,
            Prefix: 'PMT',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: null,
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 31,
            Code: 'FURS',
            Name: 'Fund Utilization Request and Status',
            DocumentTypeCategoryID: 1,
            Prefix: 'FURS',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: null,
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        },
        {
            ID: 32,
            Code: 'PPE',
            Name: 'Property, Plant and Equipment',
            DocumentTypeCategoryID: 1,
            Prefix: 'PPE',
            StartNumber: 1,
            CurrentNumber: 1,
            Suffix: null,
            Active: 1,
            CreatedBy: 'system',
            CreatedDate: new Date(),
        }

        ]
      );
      console.log('✅ Seeded Document Types with initial record.');
    } else {
      console.log(`ℹ️ ${count} Document Types already exist. Skipping seeding.`);
    }
  } catch (error) {
    console.error('❌ Error seeding Document Types:', error);
  }
};
